feat: new code signing procedure for Windows (#524)
- migrated to new code signing procedure for Windows binaries;
- separated debug and release mk msi scripts;
- debug target is still using old signing process with self-signed dev cert;

Ref: LOG-17559

diff --git a/packaging/windows/msi/mk_test b/packaging/windows/msi/mk_test
--- a/packaging/windows/msi/mk_test
+++ b/packaging/windows/msi/mk_test
@@ -19,7 +19,8 @@ version=$(DISPLAY= WINEDEBUG=-all wine64 "$SRC_ROOT/$BUILD_DIR/signed/logdna-age
 [ "$version" == "$BUILD_VERSION" ] || (echo "Failed: Unexpected agent version!"; exit 1)
 # check exe is signed by Digicert
 osslsigncode extract-signature -in "$SRC_ROOT/$BUILD_DIR/signed/logdna-agent.exe" -out "$SRC_ROOT/$BUILD_DIR/signed/logdna-agent.pkcs7"
-(strings "$SRC_ROOT/$BUILD_DIR/signed/logdna-agent.pkcs7" | grep "DigiCert Inc") || (echo "Failed: Executable not signed with DigiCert!"; exit 1)
+(strings "$SRC_ROOT/$BUILD_DIR/signed/logdna-agent.pkcs7" | grep "DigiCert, Inc.") || (echo "Failed: Executable not signed by DigiCert!"; exit 1)
+(strings "$SRC_ROOT/$BUILD_DIR/signed/logdna-agent.pkcs7" | grep "Mezmo, Inc.") || (echo "Failed: Executable not signed by Mezmo!"; exit 1)
 echo
 echo @@@@@@  SUCCESS  @@@@@@
 echo
